#In this script it is important to set the RepositoryUrl in the *.csproj file

name: NuGet Generation for DoenaSoft.DVDProfilerHelper

on:
  push:
    branches:
      - master
  workflow_dispatch:
      
env:
  SOURCE_URL: https://api.nuget.org/v3/index.json
  PROJECT_FILE: DVDProfiler.Helper.csproj
  PROJECT_FOLDER: DVDProfilerHelper
  BUILD_CONFIGURATION: Release
  
jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{secrets.NUGET_API_KEY}}
          nuget-version: 'latest'
     
      - name: Restore Nuget
        run: nuget.exe restore ${{ env.SOLUTION_FILE }}
     
      - name: Setup .NET
        uses: microsoft/setup-msbuild@v2

      - name: Build AnyCPU
        run: msbuild ${{env.PROJECT_FOLDER}}/${{env.PROJECT_FILE}} -p:Configuration=${{env.BUILD_CONFIGURATION}} -p:Platform=AnyCPU

      - name: Pack Nuget
        run: nuget.exe pack ${{ env.PROJECT_FOLDER }}\${{ env.NUGET_SPEC }} -OutputDirectory ${{ env.PROJECT_FOLDER }}

      - name: Push Nuget
        run: nuget.exe push ${{ env.PROJECT_FOLDER }}\*.nupkg -ApiKey ${{secrets.NUGET_API_KEY}} -Source "${{env.SOURCE_URL}}"
